image: node:16-bullseye-slim

stages:
  - install
  - verify

cache: &global_cache
  key: $CI_COMMIT_REF_SLUG
  paths:
    - node_modules/
  policy: pull

install:
  stage: install
  image: node:16-bullseye
  script:
    - npm ci
  cache:
    <<: *global_cache
    policy: push

test:
  stage: verify
  script:
    - npm i --prefer-offline jest-junit
    - npm run test -- --ci --coverage --reporters=default --reporters=jest-junit
  artifacts:
    when: always
    paths:
      - junit.xml
      - coverage/
    reports:
      junit: junit.xml
      coverage_report:
        coverage_format: cobertura
        path: coverage/cobertura-coverage.xml

format:
  stage: verify
  script:
    - npm run format -- --check

lint:
  stage: verify
  script:
    - npm run lint
